### ISSUE TITLE
Confused by the BepInEx requirement

### ISSUE THREAD

**Issue by fleps** [Captain-Of-Coit/cs2-city-monitor#13]
In here and on the description it says to get v6-be, but on Thunderstorm "required mods" is linked to BepInEx v5 and I see videos of people using it and other mods that only have v5 support.

Which one is it? Does it work with v5?

**Comment by Woovie** [comment]
Installation instructions in the README are specific to this git repo. Builds that are located on Thunderstore are fully compatible with BepInEx 5.

**Comment by vilFML** [comment]
As @Woovie writes, the Thunderstorm files are compatible with BepinEx v5.
I created a folder on BepinEx\plugins and pasted the files downloaded via Thunderstorm's "Manual Download" option.
