### ISSUE TITLE
Resolution scaling issues

### ISSUE THREAD

**Issue by Woovie** [Captain-Of-Coit/cs2-city-monitor#7]
Hello, I play at 3840x2160, 100% text scaling. Here's how this mod looks:

![CS2ModIssue](https://github.com/Captain-Of-Coit/cs2-city-monitor/assets/7304619/9351d7e0-c11f-4095-a288-341169ad9441)

Unchecking the "Interface Scaling (Dev)" option fixes it for me, but it also makes the UI pretty small on my 32" display.

Thanks for your efforts!

**Comment by Captain-Of-Coit** [comment]
Thanks for the report! It's a known issue and impacts all of HookUI unfortunately :/ This is the issue to be tracked: https://github.com/Captain-Of-Coit/hookui/issues/4
